### ISSUE TITLE
Ability to send additional query parameters to the authorize endpoint

### ISSUE THREAD

**Issue by ayshsandu** [asgardeo/asgardeo-auth-react-sdk#154] opened 2022-12-06 10:46 UTC
**Is your feature request related to a problem? Please describe.**
Depending on the Identity Provider(IdP) capabilities , the client application needs to be able to send additional query parameters in the [Authorize request](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest) to the IdP

**Describe the solution you would prefer**
SDK has to support the ability to send additional query parameters. 

**Additional context**

**Comment by pavinduLakshan** [comment] 2023-08-01 08:15
duplicate of https://github.com/asgardeo/asgardeo-auth-react-sdk/issues/103

**Closed by pavinduLakshan** 2023-08-01 08:15 UTC
Labels: Resolution/Duplicate
