### ISSUE TITLE
Using WebWorker - Uncaught (in promise) TypeError: document.getElementById(...) is null

### ISSUE THREAD

**Issue by archendel** [asgardeo/asgardeo-auth-react-sdk#33] opened 2021-07-20 08:43 UTC
Authorization code flow is working as expected, my users are authenticated thanks the webworkers as expected.
But the following error is displayed in the browser console : 

```
Uncaught (in promise) TypeError: document.getElementById(...) is null
    i http://localhost:8082/build.js line 869 > eval line 407 > eval:1
    node_modules asgardeo/auth-react/dist/main.js?:407
    node_modules asgardeo/auth-react/dist/main.js?:407
    node_modules asgardeo/auth-react/dist/main.js?:407
    node_modules asgardeo/auth-react/dist/main.js?:16
```

Everything seems to work as expected, but this error looks quite confusing. 
When I click on the error on my browser, it shows me that the element the code is trying to find has the ID "opIFrame". In my DOM, I can actually find an iframe with the ID "rpIFrame", but I can't find any with the ID "opIFrame"

**How to reproduce:**
The error happens in the sample apps you provide and in the app I created using your package. 
I've pulled the code, edited the config.json to set storage as "webWorker" and other required fields, then started the app with "npm run start" command.

**Expected behavior:**
The error message should not appear in the browser console.

**Comment by thivi** [comment] 2022-08-05 13:47
This issue is no more reproducible. Can you confirm if you are still facing this issue?

**Comment by pavinduLakshan** [comment] 2023-08-01 10:16
Closing since this seems not to be reproducible. Please feel free to reopen if you continue to experience this issue.

**Closed** 2023-08-01 10:16 UTC
Labels: bug, Severity/Minor, Resolution/Cannot Reproduce
